sudo: false

dist: trusty

language: python

matrix:
    include:
        - os: linux
          env: PYTHON_VERSION=3.6 NUMPY_VERSION=1.12

install:
    - source .ci/conda.sh
    - python setup.py install

cache:
    directories:
        - $HOME/miniconda

after_success:
    - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then source .ci/build-docs.sh; fi
